name: Publish NPM Package
on:
    workflow_dispatch:

permissions:
    contents: write
    id-token: write

jobs:
    publish-npm-package:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: libgtk-3-dev libwebkit2gtk-4.1-dev build-essential pkg-config typescript
                  version: 1.0

            - name: Install Wails
              run: |
                  go install github.com/wailsapp/wails/v3/cmd/wails3@latest
                  echo "$HOME/go/bin" >> $GITHUB_PATH

            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Build
              run: |
                  chmod +x ./build-npm.sh
                  ./build-npm.sh

            - name: Publish Package
              run: |
                  npm publish --provenance --access public ./npm-package/dist
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
