name: Publish Core JS Package
on:
    workflow_dispatch:

permissions:
    contents: write
    id-token: write

jobs:
    publish-core-js-package:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Build
              run: |
                  chmod +x ./build-npm.sh
                  ./build-npm.sh core

            - name: Publish Package
              run: |
                  npm publish --provenance --access public ./npm-package/output/core
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
